### PR TITLE
add bors.toml

### PR DESCRIPTION
**Pull request by DutchGhost**

### CODE REVIEW

**Comment by DutchGhost** [comment]
bors ping

**Comment by DutchGhost** [comment]
bors retry

**Comment by DutchGhost** [comment]
bors try

**Review by WesleyKlop — APPROVED** [review]
Priem

**Comment by DutchGhost** [comment]
bors merge

**Comment by DutchGhost** [comment]
bors try

**Comment by DutchGhost** [comment]
bors -r

**Comment by DutchGhost** [comment]
bors retry

**Comment by DutchGhost** [comment]
bors try

**Comment by DutchGhost** [comment]
bors retry

**Pull request merged**
