### PR TITLE
Multiple changes:

### PR DESCRIPTION
**Pull request by WesleyKlop**
* Fix env file
* Bind rocket to correct address
* Add script to control the devenv

### CODE REVIEW

**Comment by WesleyKlop** [comment]
bors try

**Review by DutchGhost — COMMENTED** [review]
The `web` workflow didn't trigger on commit, but did run in the `try` build.
Maybe we should consider adding `*.yml` to https://github.com/journalio/test-rocket-app/blob/857a5f4ef90b23cdc3ba2a8353ff4d7ed6a9a145/.github/workflows/web.yml#L10-L14

Can you fix the prettier issue so we can merge this?

**Comment by WesleyKlop** [comment]
Nah we don't need to add yml I think

**Review by DutchGhost — COMMENTED** [review]
Bors try

**Review by DutchGhost — APPROVED** [review]
bors r+

**Pull request merged**
