### PR TITLE
Add bors badge to show love for bors

### LINKED ISSUE #24: Add a merge bot
Add a merge bot to the project: https://github.com/bors-ng/bors-ng

We dont neccesarily need this, but I'd like to experiment with it and use it.

The bot may be usefull within a pipeline.

### PR DESCRIPTION
**Pull request by DutchGhost**
Adds the borse badge to the repo to show love for bors <3
Closes #24

### CODE REVIEW

**Review by RdenBlaauwen — APPROVED** [review]
YAAAAY

**Comment by DutchGhost** [comment]
bors try

**Comment by DutchGhost** [comment]
bors retry

**Pull request merged**
